version: '3.9'

services:
  server:
    build: 
      context: .
    ports:
      - "3000:3000"
    container_name: fniverse_server
    volumes:
      - ./:/app
      - /app/node_modules
    links:
      - "db:db"
    depends_on:
      - db
    command: yarn start:dev
  db:
    image: mysql:8.0
    restart: always
    container_name: fniverse_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fniverse
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data: